(function(){
"use strict";
var cfg=window.FACEHUB_MINI||{},initData="",currentUser=null,currentView="home",viewStack=[],selectedBlogMedia=null;
var cache={books:null,music:null,blogs:null,poems:null,profile:null};
var audio=document.getElementById("miniAudio"),playingSong=null;
function q(s,r){return(r||document).querySelector(s)}function qa(s,r){return Array.prototype.slice.call((r||document).querySelectorAll(s))}
function byId(id){return document.getElementById(id)}function esc(s){return String(s==null?"":s).replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]})}
function showScreen(id){["loadingScreen","bindingScreen","homeScreen"].forEach(function(x){var n=byId(x);if(n)n.classList.toggle("active",x===id)})}
function parseQS(raw){var o={};raw=(raw||"").replace(/^[#?]/,"");if(!raw)return o;raw.split("&").forEach(function(p){var i=p.indexOf("="),k=i>=0?p.slice(0,i):p,v=i>=0?p.slice(i+1):"";try{k=decodeURIComponent(k.replace(/\+/g,"%20"))}catch(e){}try{v=decodeURIComponent(v.replace(/\+/g,"%20"))}catch(e){}if(!(k in o))o[k]=v});return o}
function launch(){var a=parseQS(location.search),b=parseQS(location.hash),k;for(k in b)a[k]=b[k];return a}var launchParams=launch();
function rawInit(){return launchParams[cfg.hashKey]||launchParams.tgWebAppData||launchParams.WebAppData||""}
function nativeObject(){if(cfg.platform==="telegram")return window.Telegram&&window.Telegram.WebApp?window.Telegram.WebApp:null;if(cfg.platform==="max")return window.WebApp||null;return null}
function enhance(){var n=nativeObject();try{if(n&&n.ready)n.ready();if(n&&n.expand)n.expand()}catch(e){}}
function body(action,data){var p=["action="+encodeURIComponent(action),"init_data="+encodeURIComponent(initData||"")];Object.keys(data||{}).forEach(function(k){p.push(encodeURIComponent(k)+"="+encodeURIComponent(data[k]==null?"":String(data[k]))) });return p.join("&")}
function miniApi(action,data,ok,fail){var x=new XMLHttpRequest();x.open("POST",cfg.api+"?_t="+Date.now(),true);x.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");x.withCredentials=true;x.onreadystatechange=function(){if(x.readyState!==4)return;var d={};try{d=JSON.parse(x.responseText||"{}")}catch(e){if(fail)fail("Некорректный ответ сервера");return}if(x.status<200||x.status>=300||d.success===false){if(fail)fail(d.message||"Ошибка сервера");return}if(ok)ok(d)};x.onerror=function(){if(fail)fail("Нет связи с сервером")};x.send(body(action,data))}
async function siteApi(action,data){var r=await fetch("../api.php",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams(Object.assign({action:action},data||{})).toString()});var d={};try{d=await r.json()}catch(e){throw new Error("Некорректный ответ сервера")}if(!r.ok||d.success===false)throw new Error(d.message||"Ошибка сервера");return d}
async function siteForm(fd){var r=await fetch("../api.php",{method:"POST",credentials:"same-origin",body:fd});var d=await r.json();if(!r.ok||d.success===false)throw new Error(d.message||"Ошибка сервера");return d}
function mediaUrl(path){if(!path)return"";if(/^https?:\/\//i.test(path))return path;return new URL(String(path).replace(/^\//,""),location.origin+"/").href}
function avatar(path){return path?mediaUrl(path):"data:image/svg+xml;charset=UTF-8,"+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect width="100" height="100" rx="50" fill="#e5edf4"/><circle cx="50" cy="37" r="18" fill="#8297aa"/><path d="M17 88c5-23 21-34 33-34s28 11 33 34" fill="#8297aa"/></svg>')}
function toast(t){var n=byId("miniToast");n.textContent=t;n.classList.add("show");clearTimeout(window.__mt);window.__mt=setTimeout(function(){n.classList.remove("show")},1900)}
function openSheet(id){var s=byId(id);s.classList.add("show");s.setAttribute("aria-hidden","false")}function closeSheet(id){var s=byId(id);s.classList.remove("show");s.setAttribute("aria-hidden","true");if(id==="readerSheet")qa("video",s).forEach(function(v){v.pause()})}
function openExternal(url){if(!url)return;var n=nativeObject();try{if(n&&typeof n.openLink==="function"){n.openLink(url);return}}catch(e){}window.open(url,"_blank","noopener")}
function fmtDate(v){if(!v)return"";var d=new Date(String(v).replace(" ","T"));return isNaN(d.getTime())?String(v):new Intl.DateTimeFormat("ru-RU",{day:"numeric",month:"long",year:"numeric"}).format(d)}
function textBlocks(content){try{var a=JSON.parse(content||"[]");return Array.isArray(a)?a.filter(function(b){return b.type==="text"}).map(function(b){return b.value||""}).join("\n\n"):content||""}catch(e){return content||""}}
function setHeader(title,sub,back){byId("viewTitle").textContent=title;byId("viewSubtitle").textContent=sub||cfg.label+" mini app";byId("headBack").classList.toggle("hidden",!back)}
function setActiveNav(v){qa("[data-view]").forEach(function(b){b.classList.toggle("active",b.dataset.view===v)})}
function loadingView(t){byId("viewRoot").innerHTML='<div class="empty">'+esc(t||"Загрузка…")+'</div>'}
function go(view,arg,push){if(push!==false&&currentView!==view)viewStack.push({view:currentView,arg:null});currentView=view;setActiveNav(view);window.scrollTo(0,0);renderView(view,arg)}
function goBack(){var prev=viewStack.pop();if(prev){currentView=prev.view;setActiveNav(currentView);renderView(prev.view,prev.arg)}else go("home",null,false)}

function renderHome(){
 setHeader("facehub",cfg.label+" mini app",false);var name=[currentUser.first_name,currentUser.last_name].filter(Boolean).join(" ")||"вас";
 byId("viewRoot").innerHTML='<section class="view-hero"><div class="kicker">Авторское пространство</div><h1>Здравствуйте, '+esc(name.split(" ")[0])+'</h1><p>Выберите раздел. Каждый экран адаптирован под вертикальный формат mini app.</p></section>'+
 '<section class="home-grid">'+
 homeCard("books","▤","Книги","библиотека, файлы и трейлеры")+
 homeCard("music","♪","Музыка","альбомы и композиции")+
 homeCard("poetry","✦","Стихи","архив текстов")+
 homeCard("blog","◫","Блог","публикации и медиа")+
 '<button class="home-card portfolio" type="button" data-home-view="profile"><span class="home-icon">Я</span><span><b>Портфолио</b><span>профиль, данные аккаунта и доступы</span></span><span class="chevron">›</span></button></section>';
 qa("[data-home-view]",byId("viewRoot")).forEach(function(b){b.onclick=function(){go(b.dataset.homeView)}})
}
function homeCard(v,icon,title,desc){return'<button class="home-card" type="button" data-home-view="'+v+'"><span class="home-icon">'+icon+'</span><b>'+title+'</b><span>'+desc+'</span></button>'}

async function loadBooks(force){if(cache.books&&!force)return cache.books;var d=await siteApi("get_books");cache.books=Array.isArray(d.books)?d.books:[];return cache.books}
async function renderBooks(){
 setHeader("Книги","библиотека",true);loadingView("Загружаю библиотеку…");
 try{var books=await loadBooks();var h='<section class="view-hero"><div class="kicker">Библиотека</div><h1>Книги</h1><p>Вертикальная версия книжной полки без фоновых иллюстраций.</p></section><div class="book-list">';
 if(!books.length)h+='<div class="empty">Книг пока нет.</div>';
 books.forEach(function(b){h+='<button class="book-card" type="button" data-book="'+b.id+'"><span class="book-cover '+(b.cover?"":"no-cover")+'" '+(b.cover?'style="background-image:url(\''+esc(mediaUrl(b.cover))+'\')"':"")+'>'+(b.cover?"":esc(b.title))+'</span><span class="book-copy"><strong>'+esc(b.title||"Без названия")+'</strong><p>'+esc(b.annotation||"Открыть информацию о книге")+'</p><small>'+esc(b.page_count?b.page_count+" стр.":"Информация о книге")+'</small></span><span class="chevron">›</span></button>'});h+="</div>";byId("viewRoot").innerHTML=h;qa("[data-book]",byId("viewRoot")).forEach(function(b){b.onclick=function(){renderBookDetail(Number(b.dataset.book))}})
 }catch(e){byId("viewRoot").innerHTML='<div class="empty">Не удалось загрузить книги.</div>'}
}
async function renderBookDetail(id){
 setHeader("Книга","информация и материалы",true);loadingView("Загружаю книгу…");
 try{var d=await siteApi("get_book_details",{book_id:id}),b=d.book;if(!b)throw new Error();var admin=currentUser.role==="admin",access=!!d.has_access;
 var ebookAllowed=admin||Number(b.price_ebook||0)===0||access,audioAllowed=admin||Number(b.price_audio||0)===0||access;
 var h='<article class="book-detail"><div class="book-detail-top"><div class="book-detail-cover" '+(b.cover?'style="background-image:url(\''+esc(mediaUrl(b.cover))+'\')"':"")+'></div><div class="book-detail-copy"><div class="eyebrow">Книга</div><h1>'+esc(b.title||"Без названия")+'</h1><div class="book-meta">'+esc(b.page_count?b.page_count+" страниц":"Материалы книги")+'</div></div></div><div class="book-annotation">'+esc(b.annotation||"Описание книги пока не добавлено.")+'</div>';
 var ebooks=[["EPUB",b.file_epub],["PDF",b.file_pdf],["FB2",b.file_fb2]].filter(function(x){return x[1]}),audios=[["Аудио",b.file_audio],["M4B",b.file_m4b]].filter(function(x){return x[1]});
 if(ebooks.length){h+='<section class="action-group"><div class="action-group-title">Электронная книга</div><div class="action-stack">';ebooks.forEach(function(x){h+=resourceRow(x[0],x[1],ebookAllowed,"⇩")});h+="</div></section>"}
 if(audios.length){h+='<section class="action-group"><div class="action-group-title">Аудиокнига</div><div class="action-stack">';audios.forEach(function(x){h+=resourceRow(x[0],x[1],audioAllowed,"♪")});h+="</div></section>"}
 var ext=[["ЛитРес",b.litres_link],["Букмейт",b.bookmate_link],["Строки",b.stroki_link]].filter(function(x){return x[1]});
 if(ext.length){h+='<section class="action-group"><div class="action-group-title">Открыть в приложении</div><div class="external-buttons">';ext.forEach(function(x){h+='<a href="'+esc(x[1])+'" data-external="'+esc(x[1])+'">'+esc(x[0])+'</a>'});h+="</div></section>"}
 if(b.trailer_file||b.trailer_link){h+='<section class="action-group"><div class="action-group-title">Трейлер</div>';if(b.trailer_file)h+='<button class="trailer-link" type="button" id="bookTrailerButton">▶ Смотреть трейлер</button>';else h+='<button class="trailer-link" type="button" data-external="'+esc(b.trailer_link)+'">▶ Открыть трейлер</button>';h+="</section>"}
 h+="</article>";byId("viewRoot").innerHTML=h;
 qa("[data-external]",byId("viewRoot")).forEach(function(a){a.onclick=function(e){e.preventDefault();openExternal(a.dataset.external)}});
 if(b.trailer_file)byId("bookTrailerButton").onclick=function(){byId("readerSheetTitle").textContent="Трейлер · "+b.title;byId("readerSheetBody").innerHTML='<div class="trailer-box"><video controls playsinline preload="metadata" src="'+esc(mediaUrl(b.trailer_file))+'" '+(b.cover?'poster="'+esc(mediaUrl(b.cover))+'"':"")+'></video></div>';openSheet("readerSheet")}
 }catch(e){byId("viewRoot").innerHTML='<div class="empty">Не удалось открыть книгу.</div>'}
}
function resourceRow(label,path,allowed,icon){var file=String(path).split("/").pop();return'<div class="resource-row"><span class="resource-icon">'+icon+'</span><span class="resource-copy"><b>'+esc(label)+'</b><span>'+esc(decodeURIComponent(file||"файл"))+'</span></span>'+(allowed?'<a class="resource-action primary" href="'+esc(mediaUrl(path))+'" download>Скачать</a>':'<button class="resource-action locked" type="button" data-locked>Нет доступа</button>')+'</div>'}

async function loadMusic(force){if(cache.music&&!force)return cache.music;var d=await siteApi("get_music_data");cache.music={albums:Array.isArray(d.albums)?d.albums:[],songs:Array.isArray(d.songs)?d.songs:[]};return cache.music}
async function renderMusic(){
 setHeader("Музыка","фонотека",true);loadingView("Загружаю музыку…");
 try{var m=await loadMusic(),h='<section class="view-hero"><div class="kicker">Личная фонотека</div><h1>Музыка</h1><p>Альбомы и композиции в вертикальной раскладке. Список песен прокручивается вместе со страницей.</p></section>';
 h+='<section class="album-list">';if(!m.albums.length)h+='<div class="empty">Альбомов пока нет.</div>';m.albums.forEach(function(a){var count=m.songs.filter(function(s){return Number(s.album_id)===Number(a.id)}).length;h+='<article class="album-card"><div class="album-main"><div class="album-art" '+(a.cover?'style="background-image:url(\''+esc(mediaUrl(a.cover))+'\')"':"")+'></div><div class="album-copy"><h3>'+esc(a.title||"Без названия")+'</h3><p>'+esc(a.description||"")+'</p><small>'+esc([a.release_year||a.year,count?count+" комп.":""].filter(Boolean).join(" · "))+'</small></div></div>'+(a.yandex_link?'<a class="yandex-link" href="'+esc(a.yandex_link)+'" data-external="'+esc(a.yandex_link)+'"><img src="../assets/brand/yandex-music.svg" alt=""><span><b>Слушать в Яндекс.Музыке</b>Открыть альбом в приложении</span></a>':"")+'</article>'});h+='</section><div class="songs-title"><h2>Композиции</h2><span>'+m.songs.length+'</span></div><section class="song-list">';
 if(!m.songs.length)h+='<div class="empty">Композиции пока не добавлены.</div>';m.songs.forEach(function(s){var cover=s.cover||(m.albums.find(function(a){return Number(a.id)===Number(s.album_id)})||{}).cover;h+='<article class="song-row" data-song-detail="'+s.id+'"><div class="song-cover" '+(cover?'style="background-image:url(\''+esc(mediaUrl(cover))+'\')"':"")+'>'+(cover?"":"♪")+'</div><div class="song-copy"><strong>'+esc(s.title||"Без названия")+'</strong><span>'+esc([s.album_title,s.genre,s.release_year].filter(Boolean).join(" · "))+'</span></div><button class="song-play" type="button" data-play-song="'+s.id+'">▶</button></article>'});h+='</section><div class="audio-dock hidden" id="audioDock"><div class="audio-dock-cover" id="audioDockCover">♪</div><div class="audio-dock-copy"><strong id="audioDockTitle">Композиция</strong><span id="audioDockSub">Воспроизведение</span></div><button id="audioDockToggle" type="button">Ⅱ</button></div>';
 byId("viewRoot").innerHTML=h;qa("[data-external]",byId("viewRoot")).forEach(function(a){a.onclick=function(e){e.preventDefault();openExternal(a.dataset.external)}});qa("[data-play-song]",byId("viewRoot")).forEach(function(b){b.onclick=function(e){e.stopPropagation();playSong(Number(b.dataset.playSong))}});qa("[data-song-detail]",byId("viewRoot")).forEach(function(r){r.onclick=function(){openSongDetail(Number(r.dataset.songDetail))}});var t=byId("audioDockToggle");if(t)t.onclick=toggleAudio;if(playingSong)updateAudioDock()
 }catch(e){byId("viewRoot").innerHTML='<div class="empty">Не удалось загрузить музыку.</div>'}
}
async function playSong(id){var m=await loadMusic(),s=m.songs.find(function(x){return Number(x.id)===Number(id)});if(!s||!s.file_path){toast("Для песни не загружен аудиофайл");return}playingSong=s;audio.src=mediaUrl(s.file_path);audio.play().catch(function(){toast("Не удалось запустить воспроизведение")});updateAudioDock()}
function updateAudioDock(){var d=byId("audioDock");if(!d||!playingSong)return;d.classList.remove("hidden");byId("audioDockTitle").textContent=playingSong.title||"Композиция";byId("audioDockSub").textContent=playingSong.album_title||playingSong.music_author||"facehub";var m=cache.music||{albums:[]},a=m.albums.find(function(x){return Number(x.id)===Number(playingSong.album_id)}),cover=playingSong.cover||(a&&a.cover);byId("audioDockCover").style.backgroundImage=cover?'url("'+mediaUrl(cover)+'")':"";byId("audioDockCover").textContent=cover?"":"♪";byId("audioDockToggle").textContent=audio.paused?"▶":"Ⅱ"}
function toggleAudio(){if(!playingSong)return;if(audio.paused)audio.play();else audio.pause();updateAudioDock()}
function openSongDetail(id){var m=cache.music,s=m&&m.songs.find(function(x){return Number(x.id)===Number(id)});if(!s)return;byId("readerSheetTitle").textContent=s.title||"Композиция";byId("readerSheetBody").innerHTML='<div class="reader-meta">'+esc([s.album_title,s.genre,s.release_year].filter(Boolean).join(" · "))+'</div><div class="profile-data"><div class="profile-line"><span>Автор слов</span><b>'+esc(s.lyrics_author||"—")+'</b></div><div class="profile-line"><span>Автор музыки</span><b>'+esc(s.music_author||"—")+'</b></div></div><div class="reader-body" style="margin-top:14px">'+esc((s.lyrics||"").trim()||"Текст песни пока не добавлен.")+'</div>';openSheet("readerSheet")}

async function loadBlogs(force){if(cache.blogs&&!force)return cache.blogs;var d=await siteApi("get_blogs");cache.blogs=Array.isArray(d.blogs)?d.blogs:[];return cache.blogs}
async function renderBlog(){
 setHeader("Блог","личный журнал",true);loadingView("Загружаю блог…");
 try{var ps=await loadBlogs(),admin=currentUser.role==="admin",visible=admin?ps:ps.filter(function(p){return p.status!=="draft"}),h='<div class="view-hero-row"><section class="view-hero"><div class="kicker">Личный журнал</div><h1>Блог</h1><p>Публикации, фото и видео в вертикальной ленте.</p></section>'+(admin?'<button class="round-add" id="addBlogPost" type="button">＋</button>':"")+'</div><section class="post-list">';
 if(!visible.length)h+='<div class="empty">Публикаций пока нет.</div>';visible.forEach(function(p){h+='<article class="post-card" data-post="'+p.id+'>'+(p.cover?(/\.(mp4|mov|webm|m4v)(?:$|[?#])/i.test(p.cover)?'<div class="post-cover"><video muted playsinline preload="metadata" src="'+esc(mediaUrl(p.cover))+'"></video></div>':'<div class="post-cover" style="background-image:url(\''+esc(mediaUrl(p.cover))+'\')"></div>'):"")+'<div class="post-content"><div class="post-meta"><span class="'+(p.status==="draft"?"post-draft":"")+'">'+esc(p.status==="draft"?"Черновик":"Публикация")+'</span><span>'+esc(fmtDate(p.created_at))+'</span></div><h3>'+esc(p.title||"Без заголовка")+'</h3><p>'+esc(p.snippet||textBlocks(p.content))+'</p></div></article>'});h+="</section>";byId("viewRoot").innerHTML=h;if(admin)byId("addBlogPost").onclick=function(){openSheet("blogComposeSheet")};qa("[data-post]",byId("viewRoot")).forEach(function(x){x.onclick=function(){openBlogPost(Number(x.dataset.post))}})
 }catch(e){byId("viewRoot").innerHTML='<div class="empty">Не удалось загрузить блог.</div>'}
}
async function openBlogPost(id){try{var d=await siteApi("get_blog_details",{blog_id:id}),p=d.blog;if(!p)throw new Error();byId("readerSheetTitle").textContent=p.title||"Публикация";var h='<div class="reader-meta">'+esc(fmtDate(p.created_at))+'</div><div class="reader-body">';var blocks=[];try{blocks=JSON.parse(p.content||"[]")}catch(e){blocks=[{type:"text",value:p.content||""}]};blocks.forEach(function(b){if(b.type==="text")h+='<p>'+esc(b.value||"").replace(/\n/g,"<br>")+'</p>';else if(b.type==="image"||b.type==="photo")h+='<img src="'+esc(mediaUrl(b.value))+'" alt="">';else if(b.type==="video")h+='<video controls playsinline src="'+esc(mediaUrl(b.value))+'"></video>'});h+="</div>";byId("readerSheetBody").innerHTML=h;openSheet("readerSheet")}catch(e){toast("Не удалось открыть публикацию")}}
function pickBlogMedia(file){selectedBlogMedia=file||null;byId("miniBlogMedia").classList.toggle("hidden",!selectedBlogMedia);byId("miniBlogMediaName").textContent=selectedBlogMedia?selectedBlogMedia.name:""}
async function saveBlog(e){e.preventDefault();var title=byId("miniBlogTitle").value.trim(),text=byId("miniBlogText").value.trim();if(!title||!text)return;var btn=byId("miniBlogSave");btn.disabled=true;btn.textContent="Сохраняю…";try{var blocks=[{type:"text",value:text}];if(selectedBlogMedia){var up=new FormData();up.append("action","upload_blog_media");up.append("file",selectedBlogMedia);var u=await siteForm(up);if(u.url)blocks.push({type:selectedBlogMedia.type.indexOf("video/")===0?"video":"image",value:u.url})}var fd=new FormData();fd.append("action","save_blog");fd.append("mode","add");fd.append("title",title);fd.append("status",byId("miniBlogStatus").value);fd.append("content",JSON.stringify(blocks));fd.append("cover_mode","file");fd.append("del_cover","0");if(selectedBlogMedia)fd.append("cover",selectedBlogMedia);await siteForm(fd);e.target.reset();pickBlogMedia(null);closeSheet("blogComposeSheet");cache.blogs=null;toast("Публикация сохранена");renderBlog()}catch(err){toast(err.message||"Не удалось сохранить")}finally{btn.disabled=false;btn.textContent="Сохранить публикацию"}}

async function loadPoems(force){if(cache.poems&&!force)return cache.poems;var d=await siteApi("get_poems");cache.poems=Array.isArray(d.poems)?d.poems:[];return cache.poems}
function poemDate(p){var a=[];if(p.day)a.push(p.day);if(p.month)a.push(p.month);if(p.year)a.push(p.year);return a.join(".")}
async function renderPoetry(){setHeader("Стихи","архив текстов",true);loadingView("Загружаю стихи…");try{var ps=await loadPoems(),admin=currentUser.role==="admin";ps=ps.slice().sort(function(a,b){return Number(b.year)-Number(a.year)||Number(b.month||0)-Number(a.month||0)||Number(b.day||0)-Number(a.day||0)||Number(b.id)-Number(a.id)});var h='<div class="view-hero-row"><section class="view-hero"><div class="kicker">Архив</div><h1>Стихи</h1><p>Тексты по годам в компактной вертикальной ленте.</p></section>'+(admin?'<button class="round-add" id="addPoem" type="button">＋</button>':"")+'</div><section class="poem-list">';if(!ps.length)h+='<div class="empty">Стихов пока нет.</div>';ps.forEach(function(p){h+='<button class="poem-row" type="button" data-poem="'+p.id+'"><div class="meta"><span>'+esc(poemDate(p))+'</span><span>'+esc(p.year||"")+'</span></div><strong>'+esc(p.title||"Без названия")+'</strong><p>'+esc(p.content||"")+'</p></button>'});h+="</section>";byId("viewRoot").innerHTML=h;if(admin)byId("addPoem").onclick=function(){openSheet("poemComposeSheet")};qa("[data-poem]",byId("viewRoot")).forEach(function(b){b.onclick=function(){var p=ps.find(function(x){return Number(x.id)===Number(b.dataset.poem)});byId("readerSheetTitle").textContent=p.title||"Стих";byId("readerSheetBody").innerHTML='<div class="reader-meta">'+esc(poemDate(p))+'</div><div class="reader-body">'+esc(p.content||"")+'</div>';openSheet("readerSheet")}})}catch(e){byId("viewRoot").innerHTML='<div class="empty">Не удалось загрузить стихи.</div>'}}
async function savePoem(e){e.preventDefault();var btn=byId("miniPoemSave");btn.disabled=true;btn.textContent="Сохраняю…";try{await siteApi("save_poem",{mode:"add",title:byId("miniPoemTitle").value.trim(),year:byId("miniPoemYear").value,month:byId("miniPoemMonth").value,day:byId("miniPoemDay").value,content:byId("miniPoemText").value.trim()});e.target.reset();byId("miniPoemYear").value=new Date().getFullYear();closeSheet("poemComposeSheet");cache.poems=null;toast("Стих добавлен");renderPoetry()}catch(err){toast(err.message||"Не удалось сохранить")}finally{btn.disabled=false;btn.textContent="Добавить стих"}}

async function renderProfile(){setHeader("Портфолио","профиль",true);loadingView("Загружаю профиль…");try{var d=await siteApi("get_profile"),u=d.user;cache.profile=u;var full=[u.last_name,u.first_name,u.patronymic].filter(Boolean).join(" ")||u.email||"Профиль";var h='<section class="view-hero"><div class="kicker">Портфолио</div><h1>Профиль</h1><p>Данные аккаунта в мобильном формате.</p></section><article class="profile-card"><div class="profile-top"><img class="profile-avatar" src="'+esc(avatar(u.avatar_thumb))+'" alt=""><div class="profile-name"><strong>'+esc(full)+'</strong><span>'+esc(u.email||"")+'</span></div></div><div class="profile-data"><div class="profile-line"><span>Роль</span><b>'+esc(u.role==="admin"?"Администратор":"Пользователь")+'</b></div><div class="profile-line"><span>ID</span><b>'+esc(u.user_code||u.id||"—")+'</b></div></div><form class="profile-form" id="miniProfileForm"><div class="two"><label class="field"><span>Имя</span><input id="pfFirst" value="'+esc(u.first_name||"")+'"></label><label class="field"><span>Фамилия</span><input id="pfLast" value="'+esc(u.last_name||"")+'"></label></div><label class="field"><span>Отчество</span><input id="pfPatronymic" value="'+esc(u.patronymic||"")+'"></label><div class="two"><label class="field"><span>Дата рождения</span><input id="pfDob" value="'+esc(u.dob||"")+'"></label><label class="field"><span>Город</span><input id="pfCity" value="'+esc(u.city||"")+'"></label></div><button class="primary-action" type="submit">Сохранить профиль</button></form></article>';byId("viewRoot").innerHTML=h;byId("miniProfileForm").onsubmit=saveProfile}catch(e){byId("viewRoot").innerHTML='<div class="empty">Не удалось загрузить профиль.</div>'}}
async function saveProfile(e){e.preventDefault();try{await siteApi("update_profile",{first_name:byId("pfFirst").value.trim(),last_name:byId("pfLast").value.trim(),patronymic:byId("pfPatronymic").value.trim(),dob:byId("pfDob").value.trim(),city:byId("pfCity").value.trim()});toast("Профиль сохранён");cache.profile=null}catch(err){toast(err.message||"Не удалось сохранить")}}

function renderView(v,arg){if(v==="home")renderHome();else if(v==="books")renderBooks();else if(v==="music")renderMusic();else if(v==="blog")renderBlog();else if(v==="poetry")renderPoetry();else if(v==="profile")renderProfile()}
function renderHomeSession(u){currentUser=u||{};var nm=[u.first_name,u.last_name].filter(Boolean).join(" ")||u.email||"П";byId("userAvatar").src=avatar(u.avatar_thumb);byId("userInitial").textContent=(nm.trim()[0]||"П").toUpperCase();byId("userAvatar").onload=function(){byId("userInitial").style.display="none"};showScreen("homeScreen");enhance();viewStack=[];currentView="home";renderHome()}
function showBinding(msg,allow){byId("bindingText").textContent=msg||("Свяжите "+cfg.label+" с существующим аккаунтом facehub.");byId("bindingError").textContent="";byId("loginForm").classList.toggle("hidden",allow===false);byId("compatNote").textContent=initData?"Данные запуска получены. Привязка выполняется защищённо на сервере.":"Не получены данные запуска "+cfg.label+". Откройте mini app повторно из бота.";showScreen("bindingScreen")}
function bootstrap(raw){initData=raw||"";if(!initData){showBinding("Не удалось получить данные запуска "+cfg.label+".",false);return}byId("loadingStatus").textContent="Проверяю привязку…";miniApi("bootstrap",{},function(d){if(d.status==="authenticated"&&d.user){renderHomeSession(d.user);return}if(d.site_session){byId("currentSessionButton").classList.remove("hidden");showBinding("Найден аккаунт "+d.site_session.email+". Его можно привязать без повторного ввода пароля.",true)}else showBinding(null,true)},function(m){showBinding(m,true);byId("bindingError").textContent=m})}
function discover(){var r=rawInit();if(r){bootstrap(r);return}var tries=0,t=setInterval(function(){tries++;var n=nativeObject(),d=n&&typeof n.initData==="string"?n.initData:"";if(d){clearInterval(t);bootstrap(d)}else if(tries>=24){clearInterval(t);bootstrap("")}},200)}
function bindLogin(e){e.preventDefault();var b=byId("loginButton");b.disabled=true;miniApi("bind_login",{email:byId("email").value.trim().toLowerCase(),password:byId("password").value},function(d){b.disabled=false;if(d.user)renderHomeSession(d.user)},function(m){b.disabled=false;byId("bindingError").textContent=m})}
function bindCurrent(){miniApi("bind_current_session",{},function(d){if(d.user)renderHomeSession(d.user)},function(m){byId("bindingError").textContent=m})}
function initUI(){byId("loginForm").onsubmit=bindLogin;byId("currentSessionButton").onclick=bindCurrent;byId("headBack").onclick=goBack;byId("profileButton").onclick=function(){go("profile")};qa("[data-view]").forEach(function(b){b.onclick=function(){viewStack=[];go(b.dataset.view,null,false)}});qa("[data-close-sheet]").forEach(function(b){b.onclick=function(){closeSheet(b.dataset.closeSheet)}});qa(".sheet").forEach(function(s){s.addEventListener("click",function(e){if(e.target===s)closeSheet(s.id)})});byId("miniBlogForm").onsubmit=saveBlog;byId("miniBlogCamera").onchange=function(){pickBlogMedia(this.files&&this.files[0])};byId("miniBlogGallery").onchange=function(){pickBlogMedia(this.files&&this.files[0])};byId("miniBlogMediaClear").onclick=function(){byId("miniBlogCamera").value="";byId("miniBlogGallery").value="";pickBlogMedia(null)};byId("miniPoemForm").onsubmit=savePoem;byId("miniPoemYear").value=new Date().getFullYear();audio.addEventListener("play",updateAudioDock);audio.addEventListener("pause",updateAudioDock);enhance();discover()}
window.FacehubMini={openView:go,nativeObject:nativeObject};
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",initUI);else initUI();
}());