(function(){
"use strict";
var cfg=window.FACEHUB_MINI||{},initData="",currentUser=null,launchParams=parseLaunchParams(),blogs=[],poems=[];
function q(s){return document.querySelector(s)} function qa(s){return Array.prototype.slice.call(document.querySelectorAll(s))}
function byId(id){return document.getElementById(id)}
function showScreen(id){["loadingScreen","bindingScreen","homeScreen"].forEach(function(x){var n=byId(x);if(n)n.classList.toggle("active",x===id)})}
function parseQS(raw){var o={};raw=(raw||"").replace(/^[#?]/,"");if(!raw)return o;raw.split("&").forEach(function(p){var i=p.indexOf("="),k=i>=0?p.slice(0,i):p,v=i>=0?p.slice(i+1):"";try{k=decodeURIComponent(k.replace(/\+/g,"%20"))}catch(e){}try{v=decodeURIComponent(v.replace(/\+/g,"%20"))}catch(e){}if(!(k in o))o[k]=v});return o}
function parseLaunchParams(){var a=parseQS(location.search),b=parseQS(location.hash),k;for(k in b)a[k]=b[k];return a}
function rawInit(){return launchParams[cfg.hashKey]||launchParams.tgWebAppData||launchParams.WebAppData||""}
function nativeObject(){if(cfg.platform==="telegram")return window.Telegram&&window.Telegram.WebApp?window.Telegram.WebApp:null;if(cfg.platform==="max")return window.WebApp||null;return null}
function enhance(){var n=nativeObject();if(!n){runtime(false);return}try{if(n.ready)n.ready();if(n.expand)n.expand()}catch(e){}runtime(true)}
function runtime(ok){var n=byId("runtimeInfo");if(n)n.textContent=cfg.label+(ok?" · mini app":" · совместимый режим")}
function body(action,data){var p=["action="+encodeURIComponent(action),"init_data="+encodeURIComponent(initData||"")];data=data||{};Object.keys(data).forEach(function(k){p.push(encodeURIComponent(k)+"="+encodeURIComponent(data[k]==null?"":String(data[k]))) });return p.join("&")}
function miniApi(action,data,ok,fail){var x=new XMLHttpRequest();x.open("POST",cfg.api+"?_t="+Date.now(),true);x.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");x.withCredentials=true;x.onreadystatechange=function(){if(x.readyState!==4)return;var d={};try{d=JSON.parse(x.responseText||"{}")}catch(e){if(fail)fail("Некорректный ответ сервера");return}if(x.status<200||x.status>=300||d.success===false){if(fail)fail(d.message||"Ошибка сервера");return}if(ok)ok(d)};x.onerror=function(){if(fail)fail("Нет связи с сервером")};x.send(body(action,data))}
async function siteApi(action,data){var r=await fetch("../api.php",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams(Object.assign({action:action},data||{})).toString()});var d=await r.json();if(!r.ok||d.success===false)throw new Error(d.message||"Ошибка сервера");return d}
function avatar(path){return path?/^https?:/.test(path)?path:"../"+String(path).replace(/^\/+/, ""):"data:image/svg+xml;charset=UTF-8,"+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect width="100" height="100" rx="50" fill="#e5edf4"/><circle cx="50" cy="37" r="18" fill="#8297aa"/><path d="M17 88c5-23 21-34 33-34s28 11 33 34" fill="#8297aa"/></svg>')}
function withMini(t){return t+(t.indexOf("?")>=0?"&":"?")+"mini="+encodeURIComponent(cfg.platform)}
function wireLinks(){qa("[data-target]").forEach(function(a){a.href=withMini(a.getAttribute("data-target"))})}
function toast(t){var n=byId("miniToast");n.textContent=t;n.classList.add("show");clearTimeout(window.__mt);window.__mt=setTimeout(function(){n.classList.remove("show")},1800)}
function cleanBlocks(c){try{return JSON.parse(c||"[]").filter(function(b){return b.type==="text"}).map(function(b){return b.value||""}).join("\n\n")}catch(e){return c||""}}
function fmt(v){if(!v)return "";var d=new Date(String(v).replace(" ","T"));return isNaN(d)?String(v):new Intl.DateTimeFormat("ru-RU",{day:"numeric",month:"short"}).format(d)}
function renderFeed(items){var h=byId("recentFeed");h.innerHTML="";if(!items.length){h.innerHTML='<div class="empty-card">Пока здесь тихо.</div>';return}items.slice(0,6).forEach(function(it){var b=document.createElement("button");b.className="feed-card";b.type="button";b.innerHTML='<div class="meta"><span>'+it.kind+'</span><span>'+it.date+'</span></div><strong></strong><p></p>';b.querySelector("strong").textContent=it.title||"Без названия";b.querySelector("p").textContent=it.preview||"";b.onclick=function(){openReader(it)};h.appendChild(b)})}
function allItems(){var a=[];blogs.forEach(function(p){if(p.status!=="draft")a.push({kind:"Блог",title:p.title,date:fmt(p.created_at),sort:p.created_at||"",preview:p.snippet||cleanBlocks(p.content),body:cleanBlocks(p.content)})});poems.forEach(function(p){a.push({kind:"Стих",title:p.title,date:[p.day,p.month,p.year].filter(Boolean).join("."),sort:String(p.year||"")+"-"+String(p.month||0).padStart(2,"0")+"-"+String(p.day||0).padStart(2,"0"),preview:(p.content||"").replace(/\s+/g," "),body:p.content||""})});return a.sort(function(a,b){return b.sort.localeCompare(a.sort)})}
async function loadContent(){try{var rs=await Promise.all([siteApi("get_blogs"),siteApi("get_poems")]);blogs=rs[0].blogs||[];poems=rs[1].poems||[];byId("blogCount").textContent=blogs.filter(function(x){return x.status!=="draft"}).length+" публикаций";byId("poemCount").textContent=poems.length+" текстов";renderFeed(allItems())}catch(e){byId("recentFeed").innerHTML='<div class="empty-card">Не удалось загрузить ленту.</div>'}}
function openReader(it){byId("readerTitle").textContent=it.title||"Без названия";byId("readerMeta").textContent=it.kind+(it.date?" · "+it.date:"");byId("readerBody").textContent=it.body||it.preview||"";openSheet("readerSheet")}
function openSheet(id){var s=byId(id);s.classList.add("show");s.setAttribute("aria-hidden","false")}
function closeSheet(id){var s=byId(id);s.classList.remove("show");s.setAttribute("aria-hidden","true")}
function switchCompose(type){qa("[data-compose-tab]").forEach(function(b){b.classList.toggle("active",b.dataset.composeTab===type)});qa(".compose-form").forEach(function(f){f.classList.toggle("active",f.dataset.form===type)});openSheet("composeSheet")}
function renderHome(user){currentUser=user||{};var name=[currentUser.first_name,currentUser.last_name].filter(Boolean).join(" ")||currentUser.email||"Профиль";byId("userName").textContent=name;byId("platformState").textContent=cfg.label+" · facehub";byId("userAvatar").src=avatar(currentUser.avatar_thumb);if(currentUser.role==="admin")byId("adminPanel").classList.remove("hidden");else byId("adminPanel").classList.add("hidden");wireLinks();showScreen("homeScreen");enhance();loadContent()}
function showBinding(msg,allow){byId("bindingText").textContent=msg||("Свяжите "+cfg.label+" с аккаунтом facehub.");byId("bindingError").textContent="";byId("loginForm").classList.toggle("hidden",allow===false);byId("compatNote").textContent=initData?"Данные запуска получены. Привязка выполняется на сервере.":"Не получены данные запуска "+cfg.label+". Откройте mini app повторно из бота.";showScreen("bindingScreen")}
function bootstrap(raw){initData=raw||"";if(!initData){showBinding("Не удалось получить данные запуска "+cfg.label+".",false);return}byId("loadingStatus").textContent="Проверяю привязку…";miniApi("bootstrap",{},function(d){if(d.status==="authenticated"&&d.user){renderHome(d.user);return}if(d.site_session){byId("currentSessionButton").classList.remove("hidden");showBinding("Найден аккаунт "+d.site_session.email+". Его можно привязать без повторного ввода пароля.",true)}else showBinding(null,true)},function(m){showBinding(m,true);byId("bindingError").textContent=m})}
function discover(){var r=rawInit();if(r){bootstrap(r);return}var tries=0,t=setInterval(function(){tries++;var n=nativeObject(),d=n&&typeof n.initData==="string"?n.initData:"";if(d){clearInterval(t);bootstrap(d)}else if(tries>=24){clearInterval(t);bootstrap("")}},200)}
function bindLogin(e){e.preventDefault();var b=byId("loginButton");b.disabled=true;miniApi("bind_login",{email:byId("email").value.trim().toLowerCase(),password:byId("password").value},function(d){b.disabled=false;if(d.user)renderHome(d.user)},function(m){b.disabled=false;byId("bindingError").textContent=m})}
function bindCurrent(){miniApi("bind_current_session",{},function(d){if(d.user)renderHome(d.user)},function(m){byId("bindingError").textContent=m})}
function unbind(){if(!confirm("Отвязать "+cfg.label+" от аккаунта facehub?"))return;miniApi("unbind",{},function(){location.reload()},function(m){alert(m)})}
async function savePost(e){e.preventDefault();var title=byId("miniPostTitle").value.trim(),text=byId("miniPostText").value.trim();if(!title||!text)return;var b=byId("miniPostSave");b.disabled=true;b.textContent="Сохраняю…";try{var fd=new FormData();fd.append("action","save_blog");fd.append("mode","add");fd.append("title",title);fd.append("status",byId("miniPostStatus").value);fd.append("content",JSON.stringify([{type:"text",value:text}]));fd.append("cover_mode","file");fd.append("del_cover","0");var r=await fetch("../api.php",{method:"POST",credentials:"same-origin",body:fd}),d=await r.json();if(!d.success)throw new Error(d.message||"Ошибка");e.target.reset();closeSheet("composeSheet");toast("Пост сохранён");loadContent()}catch(err){toast(err.message||"Не удалось сохранить")}finally{b.disabled=false;b.textContent="Сохранить пост"}}
async function savePoem(e){e.preventDefault();var b=byId("miniPoemSave");b.disabled=true;b.textContent="Сохраняю…";try{var d=await siteApi("save_poem",{mode:"add",title:byId("miniPoemTitle").value.trim(),year:byId("miniPoemYear").value,month:byId("miniPoemMonth").value,day:byId("miniPoemDay").value,content:byId("miniPoemText").value.trim()});if(!d.success)throw new Error(d.message||"Ошибка");e.target.reset();byId("miniPoemYear").value=new Date().getFullYear();closeSheet("composeSheet");toast("Стих добавлен");loadContent()}catch(err){toast(err.message||"Не удалось сохранить")}finally{b.disabled=false;b.textContent="Добавить стих"}}
function initUI(){wireLinks();byId("loginForm").onsubmit=bindLogin;byId("currentSessionButton").onclick=bindCurrent;byId("unbindButton").onclick=unbind;byId("postComposeForm").onsubmit=savePost;byId("poemComposeForm").onsubmit=savePoem;byId("miniPoemYear").value=new Date().getFullYear();qa("[data-close-sheet]").forEach(function(b){b.onclick=function(){closeSheet(b.dataset.closeSheet)}});qa("[data-compose]").forEach(function(b){b.onclick=function(){switchCompose(b.dataset.compose)}});qa("[data-compose-tab]").forEach(function(b){b.onclick=function(){switchCompose(b.dataset.composeTab)}});qa("[data-open-section]").forEach(function(b){b.onclick=function(){var kind=b.dataset.openSection==="blog"?"Блог":"Стих";renderFeed(allItems().filter(function(x){return x.kind===kind}));scrollTo({top:byId("recentSection").offsetTop-10,behavior:"smooth"})}});qa("[data-nav]").forEach(function(b){b.onclick=function(){qa("[data-nav]").forEach(function(x){x.classList.remove("active")});b.classList.add("active");if(b.dataset.nav==="home"){renderFeed(allItems());scrollTo({top:0,behavior:"smooth"})}else if(b.dataset.nav==="blog"){renderFeed(allItems().filter(function(x){return x.kind==="Блог"}));scrollTo({top:byId("recentSection").offsetTop-10,behavior:"smooth"})}else if(b.dataset.nav==="poetry"){renderFeed(allItems().filter(function(x){return x.kind==="Стих"}));scrollTo({top:byId("recentSection").offsetTop-10,behavior:"smooth"})}else scrollTo({top:byId("sectionsSection").offsetTop-10,behavior:"smooth"})}});byId("profileButton").onclick=function(){location.href=withMini("../portfolio.html")};runtime(false);enhance();discover()}
window.FacehubMini={parseLaunchParams:parseLaunchParams,nativeObject:nativeObject};
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",initUI);else initUI();
}());